"""update category

Revision ID: 47fe958acabd
Revises: 92ca24847b20
Create Date: 2025-03-29 21:51:28.051490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fe958acabd'
down_revision: Union[str, None] = '92ca24847b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_parent_category_id'), 'category', ['parent_category_id'], unique=False)
    op.create_unique_constraint(None, 'category', ['slug'])
    op.drop_constraint('category_parent_category_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_category_id'], ['id'])
    op.drop_column('category', 'parent_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_parent_category_fkey', 'category', 'category', ['parent_category'], ['id'])
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_index(op.f('ix_category_parent_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_column('category', 'parent_category_id')
    # ### end Alembic commands ###
